// Runtime provisioning of the Claude Agent SDK (Shape 2 distribution).
//
// The vsix ships NO Anthropic code (the SDK + its platform binary are All-Rights-Reserved and not
// ours to redistribute). Instead, the SDK is fetched from the official npm registry onto the user's
// own machine and imported from the extension's globalStorage. This file is the provisioning layer.
//
// Phase 0 scope: the *resolver* (find an already-provisioned install) + the pinned version + path
// helpers. The actual download/verify/extract (`ensureSdk`) lands in Phase 1; the silent background
// update in Phase 2. Until something is provisioned, `resolveSdkEntry` returns undefined and the
// dual-path `loadClaudeSdk` falls back to a bare import (dev/F5 from the repo node_modules) — so dev
// behavior is unchanged.
import * as fs from 'fs';
import * as path from 'path';

/**
 * The SDK version Braid targets. The provisioner installs exactly this; the Phase 2 updater swaps the
 * globalStorage install to match it. Bump deliberately (project rule: latest stable) — and when you do:
 *   1. regenerate the download manifest (Phase 1's gen-sdk-manifest), and
 *   2. re-verify the SDK fields we consume — the SDK is imported as `any`, so tsc cannot catch API
 *      drift (knowledge.md: the Fable binary-gating lesson).
 */
export const CLAUDE_SDK_VERSION = '0.3.170';

/** The npm package we provision (its optional `-<platform>` sibling carries the claude binary). */
export const SDK_PACKAGE = '@anthropic-ai/claude-agent-sdk';

/**
 * Root that holds provisioned SDK installs. Layout (versioned dirs + a `current` pointer file) so a
 * background update can download a new version alongside the live one and flip atomically by writing one
 * small file — never deleting in-use files (Windows would lock the running claude.exe). (Phase 2)
 *   <globalStorage>/sdk/
 *     ├─ current            ← text file: the active version
 *     ├─ 0.3.170/node_modules/…
 *     └─ 0.3.171/node_modules/…
 */
export function sdkInstallDir(globalStorageDir: string): string {
  return path.join(globalStorageDir, 'sdk');
}

/** Absolute dir for one version's node_modules tree. */
export function versionDir(installDir: string, version: string): string {
  return path.join(installDir, version);
}

function pointerPath(installDir: string): string {
  return path.join(installDir, 'current');
}

/** The version the `current` pointer names, or undefined if unset. */
export function readCurrentVersion(installDir: string): string | undefined {
  try {
    return fs.readFileSync(pointerPath(installDir), 'utf8').trim() || undefined;
  } catch {
    return undefined;
  }
}

/** Flip the active version (the atomic "swap"): a single small-file write. */
export function writeCurrentVersion(installDir: string, version: string): void {
  fs.writeFileSync(pointerPath(installDir), version);
}

/**
 * Resolve the importable ESM entry of a specific version dir, or undefined if it holds no valid install.
 * A "valid install" = `<dir>/node_modules/@anthropic-ai/claude-agent-sdk/package.json` exists AND its
 * resolved entry file exists (guards against a half-extracted tree being imported). Thin over fs.
 */
export function resolveSdkEntryInDir(dir: string | undefined): string | undefined {
  if (!dir) return undefined;
  const pkgDir = path.join(dir, 'node_modules', '@anthropic-ai', 'claude-agent-sdk');
  const pkgJsonPath = path.join(pkgDir, 'package.json');
  if (!fs.existsSync(pkgJsonPath)) return undefined;

  // Entry: exports['.'].default (string or object) → main → sdk.mjs. The SDK is `type: module`.
  let entryRel = 'sdk.mjs';
  try {
    const pkg = JSON.parse(fs.readFileSync(pkgJsonPath, 'utf8'));
    const dot = pkg?.exports?.['.'];
    const fromExports = typeof dot === 'string' ? dot : dot?.default;
    entryRel = fromExports || pkg?.main || 'sdk.mjs';
  } catch {
    /* malformed package.json → fall back to sdk.mjs */
  }
  const entry = path.join(pkgDir, entryRel);
  return fs.existsSync(entry) ? entry : undefined;
}

/** Resolve the entry of the install dir's *currently active* version (via the `current` pointer). */
export function resolveSdkEntry(installDir: string | undefined): string | undefined {
  if (!installDir) return undefined;
  const ver = readCurrentVersion(installDir);
  return ver ? resolveSdkEntryInDir(versionDir(installDir, ver)) : undefined;
}

// ---- Download manifest (media/sdk-manifest.json, generated by scripts/gen-sdk-manifest.mjs) ----

/** One package to fetch: official registry tarball + sha512 integrity + its node_modules install path. */
export interface SdkPkgEntry {
  name: string;
  path: string;        // node_modules-relative install path (the lock key, preserves nesting)
  version: string;
  tarball: string;     // official npm registry URL
  integrity: string;   // "sha512-<base64>"
  os?: string[];
  cpu?: string[];
  libc?: string[];
}

export interface SdkManifest {
  version: string;
  source?: string;
  common: SdkPkgEntry[];    // platform-independent JS closure (download all)
  platform: SdkPkgEntry[];  // per-platform binary packages (download the one matching the runtime)
}

export interface PlatformId { platform: string; arch: string; isMusl?: boolean }

/** Pick the single platform binary package matching the runtime, or undefined if none. Pure (testable). */
export function selectPlatformPackage(platformPkgs: SdkPkgEntry[], id: PlatformId): SdkPkgEntry | undefined {
  const cands = platformPkgs.filter(
    (p) => (p.os?.includes(id.platform) ?? false) && (p.cpu?.includes(id.arch) ?? false),
  );
  if (cands.length <= 1) return cands[0];
  // Multiple candidates (linux glibc vs musl) → disambiguate by libc; no libc constraint = glibc-ish.
  const wantMusl = !!id.isMusl;
  return (
    cands.find((p) => {
      const libc = p.libc;
      if (!libc || libc.length === 0) return !wantMusl;
      return wantMusl ? libc.includes('musl') : libc.includes('glibc');
    }) ?? cands[0]
  );
}

/** Read + shallow-validate the shipped download manifest. Returns undefined if missing/malformed. */
export function loadManifest(extensionPath: string): SdkManifest | undefined {
  try {
    const m = JSON.parse(fs.readFileSync(path.join(extensionPath, 'media', 'sdk-manifest.json'), 'utf8'));
    if (!m || typeof m.version !== 'string' || !Array.isArray(m.common) || !Array.isArray(m.platform)) return undefined;
    return m as SdkManifest;
  } catch {
    return undefined;
  }
}

/** A complete provision = the `current` pointer names `version` AND that version's entry resolves. */
export function isProvisioned(installDir: string, version: string): boolean {
  return readCurrentVersion(installDir) === version && !!resolveSdkEntry(installDir);
}

/** Bundled CLI binary filename for the current platform. */
function claudeBinaryName(): string {
  return process.platform === 'win32' ? 'claude.exe' : 'claude';
}

/**
 * Given a resolved SDK entry (…/@anthropic-ai/claude-agent-sdk/sdk.mjs), locate the `claude` binary that
 * ships in the sibling `@anthropic-ai/claude-agent-sdk-<platform>` package. Used for CLI subcommands the
 * SDK doesn't expose (e.g. `claude auth logout`). Returns undefined if not found. Thin over fs.
 */
export function resolveClaudeBinaryFromEntry(sdkEntry: string | undefined): string | undefined {
  if (!sdkEntry) return undefined;
  const scopeDir = path.dirname(path.dirname(sdkEntry)); // …/@anthropic-ai
  const bin = claudeBinaryName();
  try {
    for (const name of fs.readdirSync(scopeDir)) {
      if (name.startsWith('claude-agent-sdk-') && name !== 'claude-agent-sdk') {
        const p = path.join(scopeDir, name, bin);
        if (fs.existsSync(p)) return p;
      }
    }
  } catch {
    /* scope dir missing → undefined */
  }
  return undefined;
}
